require: rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  RubyInterpreters:
    - ruby
  Exclude:
    - vendor/**/*
    - .bundle/**/*
Style/Documentation:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: exploded
Layout/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 12
